name: chromatic_pr_on_push

on: pull_request

jobs:
  chromatic_pr_on_push:
    if: (github.event.pull_request.draft == false && !contains(github.head_ref, 'renovate/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: StorybookTest
        uses: ./.github/actions/storybook_test
      - name: Chromatic
        uses: ./.github/actions/chromatic
        with:
          G_TOKEN: ${{ secrets.G_TOKEN }}
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}